Only start HTTP.sys endpoint when server is HTTP.sys
OctopusDeploy/DirectoryServicesAuthenticationProvider pull request #41
Opened 2021-05-19 01:31 UTC by tothegills

2021-05-19 23:45 UTC, MissedTheMark requested changes

2021-05-19 23:45 UTC, MissedTheMark commented on source/Server/IntegratedAuthentication/IntegratedAuthenticationHost.cs
> +            if (configuration.GetWebServer() != WebServer.HTTPsys)
This should be .HttpSys :trollface:

2021-05-19 23:45 UTC, tothegills commented on source/Server/IntegratedAuthentication/IntegratedAuthenticationHost.cs
> +            if (configuration.GetWebServer() != WebServer.HTTPsys)
OK SMARTASS

2021-05-20 01:21 UTC, MissedTheMark approved these changes
👍👍

2021-05-20 01:22 UTC, merged